# vim:fileencoding=utf-8:foldmethod=marker

[manager]
cwd = { fg = "#7daea3" }

hovered = { reversed = true, bold = true }
preview_hovered = { underline = true }

find_keyword = { fg = "#a9b665", bold = true }
find_position = { fg = "#e78a4e", bg = "reset" }

marker_copied = { fg = "#8ec07c", bg = "#8ec07c" }
marker_cut = { fg = "#d3869b", bg = "#d3869b" }
marker_marked = { fg = "#7daea3", bg = "#83a598" }
marker_selected = { fg = "#fbf1c7", bg = "#fbf1c7" }

tab_active = { fg = "#000000", bg = "#a89984" }
tab_inactive = { fg = "#a89984", bg = "#504945" }
tab_width = 1

count_copied = { fg = "#000000", bg = "#8ec07c" }
count_cut = { fg = "#000000", bg = "#d3869b" }
count_selected = { fg = "#000000", bg = "#fbf1c7" }

border_symbol = "│"
border_style = { fg = "#a89984", bold = true }

[mode]
normal_main = { fg = "#000000", bg = "#a89984", bold = true }
select_main = { fg = "#000000", bg = "#e78a4e", bold = true }
unset_main = { fg = "#000000", bg = "#a9b665", bold = true }
normal_alt = { fg = "#000000", bg = "#928374" }

[status]
overall = { bold = true, italics = true }
sep_left = { open = "", close = "" }
sep_right = { open = "", close = "" }

progress_label = { fg = "#ebdbb2", bold = true }
progress_normal = { fg = "#504945", bg = "#3c3836" }
progress_error = { fg = "#ea6962", bg = "#3c3836" }

perm_type  = { fg = "#e78a4e" }
perm_read  = { fg = "#a9b665" }
perm_write = { fg = "#ea6962" }
perm_exec  = { fg = "#a9b665" }
perm_sep   = { fg = "#665c54" }

[which]
cols = 3
mask = { bg = "reset" }
cand = { fg = "#7daea3" }
rest = { fg = "#928374" }
desc = { fg = "#e78a4e" }
separator = "  "
separator_style = { fg = "#504945" }

[confirm]
border = { fg = "#ebdbb2" }
title = { fg = "#ebdbb2" }
content = { fg = "#7daea3" }
list = { fg = "#7daea3" }
btn_yes = { fg = "#a9b665", bold = true}
btn_no = { fg = "#ea6962", bold = true}

[spot]
border = { fg = "#ebdbb2" }

[input]
border = { fg = "#ebdbb2" }
selected = { reversed = true }

[tasks]
border = { fg = "#504945" }
hovered = { underline = true }

[help]
on = { fg = "#7daea3" }
run = { fg = "#d3869b" }
hovered = { reversed = true, bold = true }
footer = { fg = "#3c3836", bg = "#a89984" }

[notify]
title_info = { fg = "#8ec07c" }
title_warn = { fg = "#fbf1c7" }
title_error = { fg = "#d3869b" }

[filetype]
rules = [
  { mime = "image/*", fg = "#d3869b" },
  { mime = "{audio,video}/*", fg = "#e78a41" },
  { mime = "application/*zip", fg = "#ea6962" },
  { mime = "application/x-{tar,bzip*,7z-compressed,xz,rar}", fg = "#ea6962" },
  { mime = "application/{pdf,doc,rtf,vnd.*}", fg = "#689d6a" },
  { name = "*", fg = "#ebdbb2" },
  { name = "*/", fg = "#a89984" },
]

