#!/bin/bash

if pgrep -x "wf-recorder" > /dev/null; then
  killall wf-recorder
  sleep 0.2
  swaync-client --close-panel
  notify-send -u low "  Recording stopped"
  exit 0
fi

declare -A AUDIO_DEVICES=(
    ["🎧 Monitor (Speaker Output)"]="alsa_output.pci-0000_00_1f.3-platform-skl_hda_dsp_generic.HiFi__Speaker__sink.monitor"
    ["🎤 Internal Mic"]="alsa_input.pci-0000_00_1f.3-platform-skl_hda_dsp_generic.HiFi__Mic1__source"
)

choose_audio_source() {
  local choice
  choice=$(printf "%s\n" "${!AUDIO_DEVICES[@]}" | rofi -theme "$HOME/.config/rofi/recording.rasi" -dmenu)
  echo "${AUDIO_DEVICES[$choice]}"
}

AUDIO_SOURCE=$(choose_audio_source)
[ -z "$AUDIO_SOURCE" ] && notify-send -u low "❌ Recording cancelled" && exit 1

OUTPUT="$HOME/Videos/recordings/rec_$(date +%Y%m%d_%H%M%S).mp4"
SHORT_OUTPUT="\$HOME/Videos/recordings/rec_$(date +%Y%m%d_%H%M%S).mp4"

GEO=$(slurp)
[ -z "$GEO" ] && notify-send -u low "❌ Recording cancelled" && exit 1

wf-recorder \
  --audio="$AUDIO_SOURCE" \
  -f "$OUTPUT" \
  -g "$GEO" & swaync-client --close-panel & notify-send -u low "  Recording started" "\nFile: $SHORT_OUTPUT"
