#!/usr/bin/env bash

notify-send --urgency low --expire-time 3000 "WIFI" "scanning nearby wifi networks...."
wifi_list=$(nmcli --fields "SECURITY,SSID,RATE" device wifi list | sed 1d | sed 's/  */ /g' | sed -E "s/WPA*.?\S/ /g" | sed "s/^--/ /g" | sed "s/  //g" | sed "/--/d")

connected=$(nmcli -fields WIFI g)
if [[ "$connected" =~ "enabled" ]]; then
	toggle="󰖪  Disable Wi-Fi"
elif [[ "$connected" =~ "disabled" ]]; then
	toggle="󰖩  Enable Wi-Fi"
fi

chosen_network=$(
  echo -e "$toggle\n$wifi_list" |
  uniq -u |
  G_MESSAGES_DEBUG=Theme rofi -dmenu -i \
    -selected-row 1 \
    -theme '~/.config/rofi/wifi.rasi' \
)
# Get name of connection
read -r chosen_id <<< "${chosen_network:3}"

if [ "$chosen_network" = "" ]; then
    exit
elif [ "$chosen_network" = "󰖩  Enable Wi-Fi" ]; then
    nmcli radio wifi on
elif [ "$chosen_network" = "󰖪  Disable Wi-Fi" ]; then
    nmcli radio wifi off
else
    success_message="You are now connected to the Wi-Fi network \"$chosen_id\"."
    saved_connections=$(nmcli -g NAME connection)
    if [[ $(echo "$saved_connections" | grep -w "$chosen_id") = "$chosen_id" ]]; then
        nmcli connection up id "$chosen_id" | grep "successfully" && notify-send --urgency low --expire-time 3000 "Connection Established" "$success_message"
    else
        if [[ "$chosen_network" =~ "" ]]; then
            wifi_password=$(
                rofi -dmenu \
                    -theme '~/.config/rofi/wifi.rasi' \
                    -theme-str ' window { height: 50px; } entry { placeholder: "Password";} '
            )
        fi
        nmcli device wifi connect "$chosen_id" password "$wifi_password" | grep "successfully" && notify-send --urgency low --expire-time 3000 "Connection Established" "$success_message"
    fi
fi
